server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.31:3306/fh_test?useUnicode=true&characterEncoding=UTF-8
    username: hhuangtech
    password: hhuang
  redis:
    host: 192.168.31.32
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        min-idle: 20
        max-idle: 200
        max-active: 200
        max-wait: 3000ms
logging:
  level:
    root: info
    com.chimera.im: debug
    com.easemob.im.http: debug
mybatis:
  mapper-locations:
    - classpath:com/hf/menu/mapper/*.xml

feige:
  msg:
    url: https://api.4321.sh/sms/send
    apikey: N853878812
    secret: 8538777b89aca791
    sign_id: 160925


